In [1]:
#importing all necessary libraries
import pandas as pd
import numpy as np

In [2]:
#uploading the datasets
county_data = pd.read_csv('data/election-context-2018.csv')
election_results = pd.read_csv('data/2018_4_0_2.csv', skiprows = [0])

In [3]:
#merging the two datasets
merged_df = county_data.merge(election_results, left_on = "fips", right_on = 'fips')
merged_df.head()

,state,county,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,...,vote13,vote14,vote15,vote16,vote17,vote18,vote19,vote20,vote21,vote22
0,Alabama,Autauga,1001,18172,5936,865,17379,6363,190,6331.0,...,0,0,0,0,0,0,0,0,0,0
1,Alabama,Baldwin,1003,72883,18458,3874,66016,18424,898,19145.0,...,0,0,0,0,0,0,0,0,0,0
2,Alabama,Barbour,1005,5454,4871,144,5550,5912,47,4777.0,...,0,0,0,0,0,0,0,0,0,0
3,Alabama,Bibb,1007,6738,1874,207,6132,2202,86,2082.0,...,0,0,0,0,0,0,0,0,0,0
4,Alabama,Blount,1009,22859,2156,573,20757,2970,279,2980.0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
#making sure each fips is unique
election_results['fips'].value_counts()

fips
1001     1
39083    1
39087    1
39089    1
39091    1
        ..
21101    1
21103    1
21105    1
21107    1
56045    1
Name: count, Length: 3151, dtype: int64

In [5]:
county_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3114 entries, 0 to 3113
Data columns (total 39 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3114 non-null   object
 1   county                  3114 non-null   object
 2   fips                    3114 non-null   int64
 3   trump16                 3114 non-null   int64
 4   clinton16               3114 non-null   int64
 5   otherpres16             3114 non-null   int64
 6   romney12                3114 non-null   int64
 7   obama12                 3114 non-null   int64
 8   otherpres12             3114 non-null   int64
 9   demsen16                1942 non-null   float64
 10  repsen16                1942 non-null   float64
 11  othersen16              1942 non-null   float64
 12  demhouse16              2862 non-null   float64
 13  rephouse16              2862 non-null   float64
 14  otherhouse16            2862 non-null   float64
 15  demgov16                601 non-null    float64
 16  repgov16                601 non-null    float64
 17  othergov16              601 non-null    float64
 18  repgov14                2148 non-null   float64
 19  demgov14                2148 non-null   float64
 20  othergov14              2148 non-null   float64
 21  total_population        3111 non-null   float64
 22  cvap                    3111 non-null   float64
 23  white_pct               3111 non-null   float64
 24  black_pct               3111 non-null   float64
 25  hispanic_pct            3111 non-null   float64
 26  nonwhite_pct            3111 non-null   float64
 27  foreignborn_pct         3111 non-null   float64
 28  female_pct              3111 non-null   float64
 29  age29andunder_pct       3111 non-null   float64
 30  age65andolder_pct       3111 non-null   float64
 31  median_hh_inc           3111 non-null   float64
 32  clf_unemploy_pct        3111 non-null   float64
 33  lesshs_pct              3111 non-null   float64
 34  lesscollege_pct         3111 non-null   float64
 35  lesshs_whites_pct       3111 non-null   float64
 36  lesscollege_whites_pct  3111 non-null   float64
 37  rural_pct               3113 non-null   float64
 38  ruralurban_cc           3113 non-null   float64
dtypes: float64(30), int64(7), object(2)
memory usage: 948.9+ KB

In [6]:
election_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3151 entries, 0 to 3150
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fips       3151 non-null   int64
 1   name       3151 non-null   object
 2   type       3151 non-null   object
 3   totalvote  3151 non-null   int64
 4   vote1      3151 non-null   int64
 5   vote2      3151 non-null   int64
 6   vote3      3151 non-null   int64
 7   vote4      3151 non-null   int64
 8   vote5      3151 non-null   int64
 9   vote6      3151 non-null   int64
 10  vote7      3151 non-null   int64
 11  vote8      3151 non-null   int64
 12  vote9      3151 non-null   int64
 13  vote10     3151 non-null   int64
 14  vote11     3151 non-null   int64
 15  vote12     3151 non-null   int64
 16  vote13     3151 non-null   int64
 17  vote14     3151 non-null   int64
 18  vote15     3151 non-null   int64
 19  vote16     3151 non-null   int64
 20  vote17     3151 non-null   int64
 21  vote18     3151 non-null   int64
 22  vote19     3151 non-null   int64
 23  vote20     3151 non-null   int64
 24  vote21     3151 non-null   int64
 25  vote22     3151 non-null   int64
dtypes: int64(24), object(2)
memory usage: 640.2+ KB

In [7]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3111 entries, 0 to 3110
Data columns (total 64 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3111 non-null   object
 1   county                  3111 non-null   object
 2   fips                    3111 non-null   int64
 3   trump16                 3111 non-null   int64
 4   clinton16               3111 non-null   int64
 5   otherpres16             3111 non-null   int64
 6   romney12                3111 non-null   int64
 7   obama12                 3111 non-null   int64
 8   otherpres12             3111 non-null   int64
 9   demsen16                1942 non-null   float64
 10  repsen16                1942 non-null   float64
 11  othersen16              1942 non-null   float64
 12  demhouse16              2862 non-null   float64
 13  rephouse16              2862 non-null   float64
 14  otherhouse16            2862 non-null   float64
 15  demgov16                601 non-null    float64
 16  repgov16                601 non-null    float64
 17  othergov16              601 non-null    float64
 18  repgov14                2148 non-null   float64
 19  demgov14                2148 non-null   float64
 20  othergov14              2148 non-null   float64
 21  total_population        3110 non-null   float64
 22  cvap                    3110 non-null   float64
 23  white_pct               3110 non-null   float64
 24  black_pct               3110 non-null   float64
 25  hispanic_pct            3110 non-null   float64
 26  nonwhite_pct            3110 non-null   float64
 27  foreignborn_pct         3110 non-null   float64
 28  female_pct              3110 non-null   float64
 29  age29andunder_pct       3110 non-null   float64
 30  age65andolder_pct       3110 non-null   float64
 31  median_hh_inc           3110 non-null   float64
 32  clf_unemploy_pct        3110 non-null   float64
 33  lesshs_pct              3110 non-null   float64
 34  lesscollege_pct         3110 non-null   float64
 35  lesshs_whites_pct       3110 non-null   float64
 36  lesscollege_whites_pct  3110 non-null   float64
 37  rural_pct               3111 non-null   float64
 38  ruralurban_cc           3111 non-null   float64
 39  name                    3111 non-null   object
 40  type                    3111 non-null   object
 41  totalvote               3111 non-null   int64
 42  vote1                   3111 non-null   int64
 43  vote2                   3111 non-null   int64
 44  vote3                   3111 non-null   int64
 45  vote4                   3111 non-null   int64
 46  vote5                   3111 non-null   int64
 47  vote6                   3111 non-null   int64
 48  vote7                   3111 non-null   int64
 49  vote8                   3111 non-null   int64
 50  vote9                   3111 non-null   int64
 51  vote10                  3111 non-null   int64
 52  vote11                  3111 non-null   int64
 53  vote12                  3111 non-null   int64
 54  vote13                  3111 non-null   int64
 55  vote14                  3111 non-null   int64
 56  vote15                  3111 non-null   int64
 57  vote16                  3111 non-null   int64
 58  vote17                  3111 non-null   int64
 59  vote18                  3111 non-null   int64
 60  vote19                  3111 non-null   int64
 61  vote20                  3111 non-null   int64
 62  vote21                  3111 non-null   int64
 63  vote22                  3111 non-null   int64
dtypes: float64(30), int64(30), object(4)
memory usage: 1.5+ MB

In [8]:
merged_df['vote6'].value_counts()

vote6
0      3020
41        2
99        2
841       2
24        2
       ...
48        1
223       1
886       1
123       1
114       1
Name: count, Length: 85, dtype: int64

In [9]:
# x = range(3,23)
# for n in x:
#     print (n)

In [10]:
list_to_drop = []
for n in range(3,23):
    list_to_drop.append("vote" + str(n))
list_to_drop

['vote3',
 'vote4',
 'vote5',
 'vote6',
 'vote7',
 'vote8',
 'vote9',
 'vote10',
 'vote11',
 'vote12',
 'vote13',
 'vote14',
 'vote15',
 'vote16',
 'vote17',
 'vote18',
 'vote19',
 'vote20',
 'vote21',
 'vote22']

In [11]:
#dropping columns
merged_df = merged_df.drop(columns = list_to_drop)
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3111 entries, 0 to 3110
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3111 non-null   object
 1   county                  3111 non-null   object
 2   fips                    3111 non-null   int64
 3   trump16                 3111 non-null   int64
 4   clinton16               3111 non-null   int64
 5   otherpres16             3111 non-null   int64
 6   romney12                3111 non-null   int64
 7   obama12                 3111 non-null   int64
 8   otherpres12             3111 non-null   int64
 9   demsen16                1942 non-null   float64
 10  repsen16                1942 non-null   float64
 11  othersen16              1942 non-null   float64
 12  demhouse16              2862 non-null   float64
 13  rephouse16              2862 non-null   float64
 14  otherhouse16            2862 non-null   float64
 15  demgov16                601 non-null    float64
 16  repgov16                601 non-null    float64
 17  othergov16              601 non-null    float64
 18  repgov14                2148 non-null   float64
 19  demgov14                2148 non-null   float64
 20  othergov14              2148 non-null   float64
 21  total_population        3110 non-null   float64
 22  cvap                    3110 non-null   float64
 23  white_pct               3110 non-null   float64
 24  black_pct               3110 non-null   float64
 25  hispanic_pct            3110 non-null   float64
 26  nonwhite_pct            3110 non-null   float64
 27  foreignborn_pct         3110 non-null   float64
 28  female_pct              3110 non-null   float64
 29  age29andunder_pct       3110 non-null   float64
 30  age65andolder_pct       3110 non-null   float64
 31  median_hh_inc           3110 non-null   float64
 32  clf_unemploy_pct        3110 non-null   float64
 33  lesshs_pct              3110 non-null   float64
 34  lesscollege_pct         3110 non-null   float64
 35  lesshs_whites_pct       3110 non-null   float64
 36  lesscollege_whites_pct  3110 non-null   float64
 37  rural_pct               3111 non-null   float64
 38  ruralurban_cc           3111 non-null   float64
 39  name                    3111 non-null   object
 40  type                    3111 non-null   object
 41  totalvote               3111 non-null   int64
 42  vote1                   3111 non-null   int64
 43  vote2                   3111 non-null   int64
dtypes: float64(30), int64(10), object(4)
memory usage: 1.0+ MB

In [12]:
#creating new columns to account for the total votes for each race 
merged_df['pres_16_total_votes'] = merged_df['trump16'] + merged_df['clinton16'] + merged_df['otherpres16']
merged_df['pres_12_total_votes'] = merged_df['romney12'] + merged_df['obama12'] + merged_df['otherpres12']
merged_df['sen_16_total_votes'] = merged_df['repsen16'] + merged_df['demsen16'] + merged_df['othersen16']
merged_df['house_16_total_votes'] = merged_df['rephouse16'] + merged_df['demhouse16'] + merged_df['otherhouse16']
merged_df

,state,county,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,...,ruralurban_cc,name,type,totalvote,vote1,vote2,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes
0,Alabama,Autauga,1001,18172,5936,865,17379,6363,190,6331.0,...,2.0,Autauga,County,19665,6221,13400,24973,23932,24613.0,24117.0
1,Alabama,Baldwin,1003,72883,18458,3874,66016,18424,898,19145.0,...,3.0,Baldwin,County,77829,17779,59992,95215,85338,93414.0,78986.0
2,Alabama,Barbour,1005,5454,4871,144,5550,5912,47,4777.0,...,6.0,Barbour,County,8354,4162,4191,10469,11509,10229.0,10046.0
3,Alabama,Bibb,1007,6738,1874,207,6132,2202,86,2082.0,...,1.0,Bibb,County,6859,1559,5299,8819,8420,8711.0,8656.0
4,Alabama,Blount,1009,22859,2156,573,20757,2970,279,2980.0,...,1.0,Blount,County,19391,1957,17420,25588,24006,25197.0,24804.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,Sweetwater,56037,12154,3231,1745,11428,4774,693,NaN,...,5.0,Sweetwater,County,12753,3959,7700,17130,16895,NaN,17309.0
3107,Wyoming,Teton,56039,3921,7314,1392,4858,6213,393,NaN,...,7.0,Teton,County,11622,7373,3843,12627,11464,NaN,12795.0
3108,Wyoming,Uinta,56041,6154,1202,1114,6615,1628,296,NaN,...,7.0,Uinta,County,6203,1256,4517,8470,8539,NaN,8570.0
3109,Wyoming,Washakie,56043,2911,532,371,3014,794,136,NaN,...,7.0,Washakie,County,3083,592,2263,3814,3944,NaN,3865.0
3110,Wyoming,Weston,56045,3033,299,194,2821,422,116,NaN,...,7.0,Weston,County,2665,372,2100,3526,3359,NaN,3572.0

In [13]:
#dropping gov because of missing null values 
list_to_drop_2 = ['demgov16', 'repgov16', 'othergov16', 'demgov14', 'repgov14', 'othergov14']
merged_df = merged_df.drop(columns = list_to_drop_2)
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3111 entries, 0 to 3110
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3111 non-null   object
 1   county                  3111 non-null   object
 2   fips                    3111 non-null   int64
 3   trump16                 3111 non-null   int64
 4   clinton16               3111 non-null   int64
 5   otherpres16             3111 non-null   int64
 6   romney12                3111 non-null   int64
 7   obama12                 3111 non-null   int64
 8   otherpres12             3111 non-null   int64
 9   demsen16                1942 non-null   float64
 10  repsen16                1942 non-null   float64
 11  othersen16              1942 non-null   float64
 12  demhouse16              2862 non-null   float64
 13  rephouse16              2862 non-null   float64
 14  otherhouse16            2862 non-null   float64
 15  total_population        3110 non-null   float64
 16  cvap                    3110 non-null   float64
 17  white_pct               3110 non-null   float64
 18  black_pct               3110 non-null   float64
 19  hispanic_pct            3110 non-null   float64
 20  nonwhite_pct            3110 non-null   float64
 21  foreignborn_pct         3110 non-null   float64
 22  female_pct              3110 non-null   float64
 23  age29andunder_pct       3110 non-null   float64
 24  age65andolder_pct       3110 non-null   float64
 25  median_hh_inc           3110 non-null   float64
 26  clf_unemploy_pct        3110 non-null   float64
 27  lesshs_pct              3110 non-null   float64
 28  lesscollege_pct         3110 non-null   float64
 29  lesshs_whites_pct       3110 non-null   float64
 30  lesscollege_whites_pct  3110 non-null   float64
 31  rural_pct               3111 non-null   float64
 32  ruralurban_cc           3111 non-null   float64
 33  name                    3111 non-null   object
 34  type                    3111 non-null   object
 35  totalvote               3111 non-null   int64
 36  vote1                   3111 non-null   int64
 37  vote2                   3111 non-null   int64
 38  pres_16_total_votes     3111 non-null   int64
 39  pres_12_total_votes     3111 non-null   int64
 40  sen_16_total_votes      1942 non-null   float64
 41  house_16_total_votes    2862 non-null   float64
dtypes: float64(26), int64(12), object(4)
memory usage: 1020.9+ KB

In [14]:
merged_df['name'].value_counts()

name
Washington    31
Franklin      26
Jefferson     26
Jackson       24
Lincoln       24
              ..
Branch         1
Benzie         1
Baraga         1
Arenac         1
Weston         1
Name: count, Length: 1804, dtype: int64

In [15]:
merged_df['county'].value_counts()

county
Washington    31
Jefferson     26
Franklin      26
Lincoln       24
Jackson       24
              ..
Branch         1
Benzie         1
Baraga         1
Arenac         1
Weston         1
Name: count, Length: 1808, dtype: int64

In [16]:
merged_df['type'].value_counts()

type
County    3006
Parish      64
City        41
Name: count, dtype: int64

In [17]:
#dropping more columns
list_to_drop_3 = ['name', 'county', 'type']
merged_df = merged_df.drop(columns = list_to_drop_3)
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3111 entries, 0 to 3110
Data columns (total 39 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3111 non-null   object
 1   fips                    3111 non-null   int64
 2   trump16                 3111 non-null   int64
 3   clinton16               3111 non-null   int64
 4   otherpres16             3111 non-null   int64
 5   romney12                3111 non-null   int64
 6   obama12                 3111 non-null   int64
 7   otherpres12             3111 non-null   int64
 8   demsen16                1942 non-null   float64
 9   repsen16                1942 non-null   float64
 10  othersen16              1942 non-null   float64
 11  demhouse16              2862 non-null   float64
 12  rephouse16              2862 non-null   float64
 13  otherhouse16            2862 non-null   float64
 14  total_population        3110 non-null   float64
 15  cvap                    3110 non-null   float64
 16  white_pct               3110 non-null   float64
 17  black_pct               3110 non-null   float64
 18  hispanic_pct            3110 non-null   float64
 19  nonwhite_pct            3110 non-null   float64
 20  foreignborn_pct         3110 non-null   float64
 21  female_pct              3110 non-null   float64
 22  age29andunder_pct       3110 non-null   float64
 23  age65andolder_pct       3110 non-null   float64
 24  median_hh_inc           3110 non-null   float64
 25  clf_unemploy_pct        3110 non-null   float64
 26  lesshs_pct              3110 non-null   float64
 27  lesscollege_pct         3110 non-null   float64
 28  lesshs_whites_pct       3110 non-null   float64
 29  lesscollege_whites_pct  3110 non-null   float64
 30  rural_pct               3111 non-null   float64
 31  ruralurban_cc           3111 non-null   float64
 32  totalvote               3111 non-null   int64
 33  vote1                   3111 non-null   int64
 34  vote2                   3111 non-null   int64
 35  pres_16_total_votes     3111 non-null   int64
 36  pres_12_total_votes     3111 non-null   int64
 37  sen_16_total_votes      1942 non-null   float64
 38  house_16_total_votes    2862 non-null   float64
dtypes: float64(26), int64(12), object(1)
memory usage: 948.0+ KB

In [18]:
merged_df['nonwhite_pct'].value_counts()

nonwhite_pct
24.316518    1
12.481699    1
2.485805     1
28.315136    1
7.531803     1
            ..
12.222393    1
3.053215     1
7.437089     1
10.540368    1
7.777003     1
Name: count, Length: 3110, dtype: int64

In [19]:
merged_df['otherpres16'].value_counts()

otherpres16
130      13
113      10
110      10
120      10
262      10
         ..
3348      1
2751      1
7066      1
22793     1
371       1
Name: count, Length: 1732, dtype: int64

In [20]:
#seeing if there were any third-party candidates with more votes than dems and reps for 2016 presidential race
third_party_df_pres_16 = merged_df.loc[(merged_df['otherpres16'] >= merged_df['trump16']) & (merged_df['otherpres16'] >= merged_df['clinton16'])]
merged_df = merged_df.loc[~merged_df['fips'].isin(third_party_df_pres_16['fips'])]
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,lesscollege_whites_pct,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,74.065601,42.002162,2.0,19665,6221,13400,24973,23932,24613.0,24117.0
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,68.405607,42.279099,3.0,77829,17779,59992,95215,85338,93414.0,78986.0
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,81.364746,67.789635,6.0,8354,4162,4191,10469,11509,10229.0,10046.0
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,87.471774,68.352607,1.0,6859,1559,5299,8819,8420,8711.0,8656.0
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,86.163610,89.951502,1.0,19391,1957,17420,25588,24006,25197.0,24804.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,76.606813,10.916313,5.0,12753,3959,7700,17130,16895,NaN,17309.0
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,41.769504,46.430920,7.0,11622,7373,3843,12627,11464,NaN,12795.0
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,81.080852,43.095937,7.0,6203,1256,4517,8470,8539,NaN,8570.0
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,75.980688,35.954529,7.0,3083,592,2263,3814,3944,NaN,3865.0
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,81.141179,54.536626,7.0,2665,372,2100,3526,3359,NaN,3572.0

In [21]:
#seeing if there were any third-party candidates with more votes than dems and reps for 2012 presidential race
third_party_df_pres_12 = merged_df.loc[(merged_df['otherpres12'] >= merged_df['romney12']) & (merged_df['otherpres12'] >= merged_df['obama12'])]
merged_df = merged_df.loc[~merged_df['fips'].isin(third_party_df_pres_12['fips'])]
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,lesscollege_whites_pct,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,74.065601,42.002162,2.0,19665,6221,13400,24973,23932,24613.0,24117.0
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,68.405607,42.279099,3.0,77829,17779,59992,95215,85338,93414.0,78986.0
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,81.364746,67.789635,6.0,8354,4162,4191,10469,11509,10229.0,10046.0
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,87.471774,68.352607,1.0,6859,1559,5299,8819,8420,8711.0,8656.0
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,86.163610,89.951502,1.0,19391,1957,17420,25588,24006,25197.0,24804.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,76.606813,10.916313,5.0,12753,3959,7700,17130,16895,NaN,17309.0
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,41.769504,46.430920,7.0,11622,7373,3843,12627,11464,NaN,12795.0
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,81.080852,43.095937,7.0,6203,1256,4517,8470,8539,NaN,8570.0
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,75.980688,35.954529,7.0,3083,592,2263,3814,3944,NaN,3865.0
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,81.141179,54.536626,7.0,2665,372,2100,3526,3359,NaN,3572.0

In [22]:
#seeing if there were any third-party candidates with more votes than dems and reps for senate race
third_party_df_sen_16 = merged_df.loc[(merged_df['othersen16'] >= merged_df['repsen16']) & (merged_df['othersen16'] >= merged_df['demsen16'])]
merged_df = merged_df.loc[~merged_df['fips'].isin(third_party_df_sen_16['fips'])]
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,lesscollege_whites_pct,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,74.065601,42.002162,2.0,19665,6221,13400,24973,23932,24613.0,24117.0
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,68.405607,42.279099,3.0,77829,17779,59992,95215,85338,93414.0,78986.0
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,81.364746,67.789635,6.0,8354,4162,4191,10469,11509,10229.0,10046.0
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,87.471774,68.352607,1.0,6859,1559,5299,8819,8420,8711.0,8656.0
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,86.163610,89.951502,1.0,19391,1957,17420,25588,24006,25197.0,24804.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,76.606813,10.916313,5.0,12753,3959,7700,17130,16895,NaN,17309.0
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,41.769504,46.430920,7.0,11622,7373,3843,12627,11464,NaN,12795.0
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,81.080852,43.095937,7.0,6203,1256,4517,8470,8539,NaN,8570.0
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,75.980688,35.954529,7.0,3083,592,2263,3814,3944,NaN,3865.0
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,81.141179,54.536626,7.0,2665,372,2100,3526,3359,NaN,3572.0

In [23]:
#seeing if there were any third-party candidates with more votes than dems and reps for house race 
third_party_df_house_16 = merged_df.loc[(merged_df['otherhouse16'] >= merged_df['rephouse16']) & (merged_df['otherhouse16'] >= merged_df['demhouse16'])]
merged_df = merged_df.loc[~merged_df['fips'].isin(third_party_df_house_16['fips'])]
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,lesscollege_whites_pct,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,74.065601,42.002162,2.0,19665,6221,13400,24973,23932,24613.0,24117.0
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,68.405607,42.279099,3.0,77829,17779,59992,95215,85338,93414.0,78986.0
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,81.364746,67.789635,6.0,8354,4162,4191,10469,11509,10229.0,10046.0
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,87.471774,68.352607,1.0,6859,1559,5299,8819,8420,8711.0,8656.0
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,86.163610,89.951502,1.0,19391,1957,17420,25588,24006,25197.0,24804.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,76.606813,10.916313,5.0,12753,3959,7700,17130,16895,NaN,17309.0
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,41.769504,46.430920,7.0,11622,7373,3843,12627,11464,NaN,12795.0
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,81.080852,43.095937,7.0,6203,1256,4517,8470,8539,NaN,8570.0
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,75.980688,35.954529,7.0,3083,592,2263,3814,3944,NaN,3865.0
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,81.141179,54.536626,7.0,2665,372,2100,3526,3359,NaN,3572.0

In [24]:
#creating new columns to get the margin of victory for the 2016 presidential election 
merged_df['pres_16_vic_size'] = merged_df['clinton16'] - merged_df['trump16']
merged_df['pres_16_mov'] = merged_df['pres_16_vic_size'] / merged_df['pres_16_total_votes']
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,ruralurban_cc,totalvote,vote1,vote2,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes,pres_16_vic_size,pres_16_mov
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,2.0,19665,6221,13400,24973,23932,24613.0,24117.0,-12236,-0.489969
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,3.0,77829,17779,59992,95215,85338,93414.0,78986.0,-54425,-0.571601
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,6.0,8354,4162,4191,10469,11509,10229.0,10046.0,-583,-0.055688
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,1.0,6859,1559,5299,8819,8420,8711.0,8656.0,-4864,-0.551536
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,1.0,19391,1957,17420,25588,24006,25197.0,24804.0,-20703,-0.809090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,5.0,12753,3959,7700,17130,16895,NaN,17309.0,-8923,-0.520899
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,7.0,11622,7373,3843,12627,11464,NaN,12795.0,3393,0.268710
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,7.0,6203,1256,4517,8470,8539,NaN,8570.0,-4952,-0.584652
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,7.0,3083,592,2263,3814,3944,NaN,3865.0,-2379,-0.623755
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,7.0,2665,372,2100,3526,3359,NaN,3572.0,-2734,-0.775383

In [25]:
#creating new columns to get the margin of victory for 2012 presidential election 
merged_df['pres_12_vic_size'] = merged_df['obama12'] - merged_df['romney12']
merged_df['pres_12_mov'] = merged_df['pres_12_vic_size'] / merged_df['pres_12_total_votes']
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,vote1,vote2,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes,pres_16_vic_size,pres_16_mov,pres_12_vic_size,pres_12_mov
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,6221,13400,24973,23932,24613.0,24117.0,-12236,-0.489969,-11016,-0.460304
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,17779,59992,95215,85338,93414.0,78986.0,-54425,-0.571601,-47592,-0.557688
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,4162,4191,10469,11509,10229.0,10046.0,-583,-0.055688,362,0.031454
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,1559,5299,8819,8420,8711.0,8656.0,-4864,-0.551536,-3930,-0.466746
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,1957,17420,25588,24006,25197.0,24804.0,-20703,-0.809090,-17787,-0.740940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,3959,7700,17130,16895,NaN,17309.0,-8923,-0.520899,-6654,-0.393844
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,7373,3843,12627,11464,NaN,12795.0,3393,0.268710,1355,0.118196
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,1256,4517,8470,8539,NaN,8570.0,-4952,-0.584652,-4987,-0.584026
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,592,2263,3814,3944,NaN,3865.0,-2379,-0.623755,-2220,-0.562880
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,372,2100,3526,3359,NaN,3572.0,-2734,-0.775383,-2399,-0.714201

In [26]:
#creating new columns to get the margin of victory for the senate
merged_df['sen_16_vic_size'] = merged_df['demsen16'] - merged_df['repsen16']
merged_df['sen_16_mov'] = merged_df['sen_16_vic_size'] / merged_df['sen_16_total_votes']
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,pres_16_total_votes,pres_12_total_votes,sen_16_total_votes,house_16_total_votes,pres_16_vic_size,pres_16_mov,pres_12_vic_size,pres_12_mov,sen_16_vic_size,sen_16_mov
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,24973,23932,24613.0,24117.0,-12236,-0.489969,-11016,-0.460304,-11889.0,-0.483037
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,95215,85338,93414.0,78986.0,-54425,-0.571601,-47592,-0.557688,-54876.0,-0.587449
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,10469,11509,10229.0,10046.0,-583,-0.055688,362,0.031454,-659.0,-0.064425
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,8819,8420,8711.0,8656.0,-4864,-0.551536,-3930,-0.466746,-4530.0,-0.520032
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,25588,24006,25197.0,24804.0,-20703,-0.809090,-17787,-0.740940,-19189.0,-0.761559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,17130,16895,NaN,17309.0,-8923,-0.520899,-6654,-0.393844,NaN,NaN
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,12627,11464,NaN,12795.0,3393,0.268710,1355,0.118196,NaN,NaN
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,8470,8539,NaN,8570.0,-4952,-0.584652,-4987,-0.584026,NaN,NaN
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,3814,3944,NaN,3865.0,-2379,-0.623755,-2220,-0.562880,NaN,NaN
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,3526,3359,NaN,3572.0,-2734,-0.775383,-2399,-0.714201,NaN,NaN

In [27]:
#creating new columns to get the margin of victory for the house
merged_df['house_16_vic_size'] = merged_df['demhouse16'] - merged_df['rephouse16']
merged_df['house_16_mov'] = merged_df['house_16_vic_size'] / merged_df['house_16_total_votes']
merged_df

,state,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,...,sen_16_total_votes,house_16_total_votes,pres_16_vic_size,pres_16_mov,pres_12_vic_size,pres_12_mov,sen_16_vic_size,sen_16_mov,house_16_vic_size,house_16_mov
0,Alabama,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,...,24613.0,24117.0,-12236,-0.489969,-11016,-0.460304,-11889.0,-0.483037,-6771.0,-0.280756
1,Alabama,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,...,93414.0,78986.0,-54425,-0.571601,-47592,-0.557688,-54876.0,-0.587449,-76995.0,-0.974793
2,Alabama,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,...,10229.0,10046.0,-583,-0.055688,362,0.031454,-659.0,-0.064425,1011.0,0.100637
3,Alabama,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,...,8711.0,8656.0,-4864,-0.551536,-3930,-0.466746,-4530.0,-0.520032,-4699.0,-0.542860
4,Alabama,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,...,25197.0,24804.0,-20703,-0.809090,-17787,-0.740940,-19189.0,-0.761559,-19977.0,-0.805394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,1745,11428,4774,693,NaN,NaN,...,NaN,17309.0,-8923,-0.520899,-6654,-0.393844,NaN,NaN,-2698.0,-0.155873
3107,Wyoming,56039,3921,7314,1392,4858,6213,393,NaN,NaN,...,NaN,12795.0,3393,0.268710,1355,0.118196,NaN,NaN,3028.0,0.236655
3108,Wyoming,56041,6154,1202,1114,6615,1628,296,NaN,NaN,...,NaN,8570.0,-4952,-0.584652,-4987,-0.584026,NaN,NaN,-3860.0,-0.450408
3109,Wyoming,56043,2911,532,371,3014,794,136,NaN,NaN,...,NaN,3865.0,-2379,-0.623755,-2220,-0.562880,NaN,NaN,-1934.0,-0.500388
3110,Wyoming,56045,3033,299,194,2821,422,116,NaN,NaN,...,NaN,3572.0,-2734,-0.775383,-2399,-0.714201,NaN,NaN,-1839.0,-0.514838

In [28]:
#dropping third parties, focusing on dems and reps
other_party_drop_list = ['otherpres12', 'otherpres16', 'othersen16', 'otherhouse16']
merged_df = merged_df.drop(columns = other_party_drop_list)
merged_df

,state,fips,trump16,clinton16,romney12,obama12,demsen16,repsen16,demhouse16,rephouse16,...,sen_16_total_votes,house_16_total_votes,pres_16_vic_size,pres_16_mov,pres_12_vic_size,pres_12_mov,sen_16_vic_size,sen_16_mov,house_16_vic_size,house_16_mov
0,Alabama,1001,18172,5936,17379,6363,6331.0,18220.0,7544.0,14315.0,...,24613.0,24117.0,-12236,-0.489969,-11016,-0.460304,-11889.0,-0.483037,-6771.0,-0.280756
1,Alabama,1003,72883,18458,66016,18424,19145.0,74021.0,0.0,76995.0,...,93414.0,78986.0,-54425,-0.571601,-47592,-0.557688,-54876.0,-0.587449,-76995.0,-0.974793
2,Alabama,1005,5454,4871,5550,5912,4777.0,5436.0,5297.0,4286.0,...,10229.0,10046.0,-583,-0.055688,362,0.031454,-659.0,-0.064425,1011.0,0.100637
3,Alabama,1007,6738,1874,6132,2202,2082.0,6612.0,1971.0,6670.0,...,8711.0,8656.0,-4864,-0.551536,-3930,-0.466746,-4530.0,-0.520032,-4699.0,-0.542860
4,Alabama,1009,22859,2156,20757,2970,2980.0,22169.0,2390.0,22367.0,...,25197.0,24804.0,-20703,-0.809090,-17787,-0.740940,-19189.0,-0.761559,-19977.0,-0.805394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,11428,4774,NaN,NaN,6536.0,9234.0,...,NaN,17309.0,-8923,-0.520899,-6654,-0.393844,NaN,NaN,-2698.0,-0.155873
3107,Wyoming,56039,3921,7314,4858,6213,NaN,NaN,7417.0,4389.0,...,NaN,12795.0,3393,0.268710,1355,0.118196,NaN,NaN,3028.0,0.236655
3108,Wyoming,56041,6154,1202,6615,1628,NaN,NaN,1826.0,5686.0,...,NaN,8570.0,-4952,-0.584652,-4987,-0.584026,NaN,NaN,-3860.0,-0.450408
3109,Wyoming,56043,2911,532,3014,794,NaN,NaN,799.0,2733.0,...,NaN,3865.0,-2379,-0.623755,-2220,-0.562880,NaN,NaN,-1934.0,-0.500388
3110,Wyoming,56045,3033,299,2821,422,NaN,NaN,621.0,2460.0,...,NaN,3572.0,-2734,-0.775383,-2399,-0.714201,NaN,NaN,-1839.0,-0.514838

In [29]:
#cols_to_drop_for_sen = ['demsen16', 'repsen16', 'sen_16_total_votes', 'sen_16_vic_size', 'sen_16_mov']
#merged_df_no_sen = merged_df.drop(columns = cols_to_drop_for_sen)

In [30]:
#detects nans or zeros for the uncontested house elections 
dem_house_nan_df = merged_df.loc[(merged_df['demhouse16'].isna()) | (merged_df['demhouse16'] == 0) | (merged_df['rephouse16'].isna()) | (merged_df['rephouse16'] == 0)]

#take all the values with nans/zeros in those rows and replace them with the values from 'pres_16_mov'
merged_df.loc[merged_df['fips'].isin(dem_house_nan_df['fips']), 'house_16_mov'] = merged_df['pres_16_mov']

merged_df

,state,fips,trump16,clinton16,romney12,obama12,demsen16,repsen16,demhouse16,rephouse16,...,sen_16_total_votes,house_16_total_votes,pres_16_vic_size,pres_16_mov,pres_12_vic_size,pres_12_mov,sen_16_vic_size,sen_16_mov,house_16_vic_size,house_16_mov
0,Alabama,1001,18172,5936,17379,6363,6331.0,18220.0,7544.0,14315.0,...,24613.0,24117.0,-12236,-0.489969,-11016,-0.460304,-11889.0,-0.483037,-6771.0,-0.280756
1,Alabama,1003,72883,18458,66016,18424,19145.0,74021.0,0.0,76995.0,...,93414.0,78986.0,-54425,-0.571601,-47592,-0.557688,-54876.0,-0.587449,-76995.0,-0.571601
2,Alabama,1005,5454,4871,5550,5912,4777.0,5436.0,5297.0,4286.0,...,10229.0,10046.0,-583,-0.055688,362,0.031454,-659.0,-0.064425,1011.0,0.100637
3,Alabama,1007,6738,1874,6132,2202,2082.0,6612.0,1971.0,6670.0,...,8711.0,8656.0,-4864,-0.551536,-3930,-0.466746,-4530.0,-0.520032,-4699.0,-0.542860
4,Alabama,1009,22859,2156,20757,2970,2980.0,22169.0,2390.0,22367.0,...,25197.0,24804.0,-20703,-0.809090,-17787,-0.740940,-19189.0,-0.761559,-19977.0,-0.805394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,11428,4774,NaN,NaN,6536.0,9234.0,...,NaN,17309.0,-8923,-0.520899,-6654,-0.393844,NaN,NaN,-2698.0,-0.155873
3107,Wyoming,56039,3921,7314,4858,6213,NaN,NaN,7417.0,4389.0,...,NaN,12795.0,3393,0.268710,1355,0.118196,NaN,NaN,3028.0,0.236655
3108,Wyoming,56041,6154,1202,6615,1628,NaN,NaN,1826.0,5686.0,...,NaN,8570.0,-4952,-0.584652,-4987,-0.584026,NaN,NaN,-3860.0,-0.450408
3109,Wyoming,56043,2911,532,3014,794,NaN,NaN,799.0,2733.0,...,NaN,3865.0,-2379,-0.623755,-2220,-0.562880,NaN,NaN,-1934.0,-0.500388
3110,Wyoming,56045,3033,299,2821,422,NaN,NaN,621.0,2460.0,...,NaN,3572.0,-2734,-0.775383,-2399,-0.714201,NaN,NaN,-1839.0,-0.514838

In [31]:
#dropping more columns
vote_size_drop = ['pres_12_total_votes', 'pres_16_total_votes', 'sen_16_total_votes', 'house_16_total_votes', 'pres_12_vic_size', 'pres_16_vic_size', 'sen_16_vic_size', 'house_16_vic_size']
merged_df = merged_df.drop(columns = vote_size_drop)
merged_df

,state,fips,trump16,clinton16,romney12,obama12,demsen16,repsen16,demhouse16,rephouse16,...,lesscollege_whites_pct,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_mov,pres_12_mov,sen_16_mov,house_16_mov
0,Alabama,1001,18172,5936,17379,6363,6331.0,18220.0,7544.0,14315.0,...,74.065601,42.002162,2.0,19665,6221,13400,-0.489969,-0.460304,-0.483037,-0.280756
1,Alabama,1003,72883,18458,66016,18424,19145.0,74021.0,0.0,76995.0,...,68.405607,42.279099,3.0,77829,17779,59992,-0.571601,-0.557688,-0.587449,-0.571601
2,Alabama,1005,5454,4871,5550,5912,4777.0,5436.0,5297.0,4286.0,...,81.364746,67.789635,6.0,8354,4162,4191,-0.055688,0.031454,-0.064425,0.100637
3,Alabama,1007,6738,1874,6132,2202,2082.0,6612.0,1971.0,6670.0,...,87.471774,68.352607,1.0,6859,1559,5299,-0.551536,-0.466746,-0.520032,-0.542860
4,Alabama,1009,22859,2156,20757,2970,2980.0,22169.0,2390.0,22367.0,...,86.163610,89.951502,1.0,19391,1957,17420,-0.809090,-0.740940,-0.761559,-0.805394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,12154,3231,11428,4774,NaN,NaN,6536.0,9234.0,...,76.606813,10.916313,5.0,12753,3959,7700,-0.520899,-0.393844,NaN,-0.155873
3107,Wyoming,56039,3921,7314,4858,6213,NaN,NaN,7417.0,4389.0,...,41.769504,46.430920,7.0,11622,7373,3843,0.268710,0.118196,NaN,0.236655
3108,Wyoming,56041,6154,1202,6615,1628,NaN,NaN,1826.0,5686.0,...,81.080852,43.095937,7.0,6203,1256,4517,-0.584652,-0.584026,NaN,-0.450408
3109,Wyoming,56043,2911,532,3014,794,NaN,NaN,799.0,2733.0,...,75.980688,35.954529,7.0,3083,592,2263,-0.623755,-0.562880,NaN,-0.500388
3110,Wyoming,56045,3033,299,2821,422,NaN,NaN,621.0,2460.0,...,81.141179,54.536626,7.0,2665,372,2100,-0.775383,-0.714201,NaN,-0.514838

In [32]:
#dropping candidates columns
candidate_drop = ['trump16', 'clinton16', 'obama12', 'romney12', 'demsen16', 'repsen16', 'demhouse16', 'rephouse16']
merged_df = merged_df.drop(columns = candidate_drop)
merged_df

,state,fips,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,...,lesscollege_whites_pct,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_mov,pres_12_mov,sen_16_mov,house_16_mov
0,Alabama,1001,55049.0,40690.0,75.683482,18.370906,2.572254,24.316518,1.838362,51.176225,...,74.065601,42.002162,2.0,19665,6221,13400,-0.489969,-0.460304,-0.483037,-0.280756
1,Alabama,1003,199510.0,151770.0,83.178788,9.225603,4.366698,16.821212,3.269510,51.194928,...,68.405607,42.279099,3.0,77829,17779,59992,-0.571601,-0.557688,-0.587449,-0.571601
2,Alabama,1005,26614.0,20375.0,45.885624,47.888329,4.309762,54.114376,2.859397,46.498084,...,81.364746,67.789635,6.0,8354,4162,4191,-0.055688,0.031454,-0.064425,0.100637
3,Alabama,1007,22572.0,17590.0,74.765196,21.212121,2.223994,25.234804,1.351232,46.464646,...,87.471774,68.352607,1.0,6859,1559,5299,-0.551536,-0.466746,-0.520032,-0.542860
4,Alabama,1009,57704.0,42430.0,87.657701,1.557951,8.727298,12.342299,4.271801,50.485235,...,86.163610,89.951502,1.0,19391,1957,17420,-0.809090,-0.740940,-0.761559,-0.805394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,44812.0,30565.0,79.815674,0.865840,15.859591,20.184326,5.509685,47.824244,...,76.606813,10.916313,5.0,12753,3959,7700,-0.520899,-0.393844,NaN,-0.155873
3107,Wyoming,56039,22623.0,16335.0,81.200548,0.614419,15.174822,18.799452,11.475048,48.097069,...,41.769504,46.430920,7.0,11622,7373,3843,0.268710,0.118196,NaN,0.236655
3108,Wyoming,56041,20893.0,14355.0,87.718375,0.186665,8.959939,12.281625,3.986981,49.327526,...,81.080852,43.095937,7.0,6203,1256,4517,-0.584652,-0.584026,NaN,-0.450408
3109,Wyoming,56043,8351.0,6135.0,82.397318,0.790325,13.962400,17.602682,3.783978,51.359119,...,75.980688,35.954529,7.0,3083,592,2263,-0.623755,-0.562880,NaN,-0.500388
3110,Wyoming,56045,7175.0,5565.0,92.222997,0.250871,1.003484,7.777003,4.083624,47.958188,...,81.141179,54.536626,7.0,2665,372,2100,-0.775383,-0.714201,NaN,-0.514838

In [33]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3098 entries, 0 to 3110
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3098 non-null   object
 1   fips                    3098 non-null   int64
 2   total_population        3097 non-null   float64
 3   cvap                    3097 non-null   float64
 4   white_pct               3097 non-null   float64
 5   black_pct               3097 non-null   float64
 6   hispanic_pct            3097 non-null   float64
 7   nonwhite_pct            3097 non-null   float64
 8   foreignborn_pct         3097 non-null   float64
 9   female_pct              3097 non-null   float64
 10  age29andunder_pct       3097 non-null   float64
 11  age65andolder_pct       3097 non-null   float64
 12  median_hh_inc           3097 non-null   float64
 13  clf_unemploy_pct        3097 non-null   float64
 14  lesshs_pct              3097 non-null   float64
 15  lesscollege_pct         3097 non-null   float64
 16  lesshs_whites_pct       3097 non-null   float64
 17  lesscollege_whites_pct  3097 non-null   float64
 18  rural_pct               3098 non-null   float64
 19  ruralurban_cc           3098 non-null   float64
 20  totalvote               3098 non-null   int64
 21  vote1                   3098 non-null   int64
 22  vote2                   3098 non-null   int64
 23  pres_16_mov             3098 non-null   float64
 24  pres_12_mov             3098 non-null   float64
 25  sen_16_mov              1929 non-null   float64
 26  house_16_mov            3098 non-null   float64
dtypes: float64(22), int64(4), object(1)
memory usage: 742.2+ KB

In [34]:
merged_df.head()

,state,fips,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,...,lesscollege_whites_pct,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_mov,pres_12_mov,sen_16_mov,house_16_mov
0,Alabama,1001,55049.0,40690.0,75.683482,18.370906,2.572254,24.316518,1.838362,51.176225,...,74.065601,42.002162,2.0,19665,6221,13400,-0.489969,-0.460304,-0.483037,-0.280756
1,Alabama,1003,199510.0,151770.0,83.178788,9.225603,4.366698,16.821212,3.269510,51.194928,...,68.405607,42.279099,3.0,77829,17779,59992,-0.571601,-0.557688,-0.587449,-0.571601
2,Alabama,1005,26614.0,20375.0,45.885624,47.888329,4.309762,54.114376,2.859397,46.498084,...,81.364746,67.789635,6.0,8354,4162,4191,-0.055688,0.031454,-0.064425,0.100637
3,Alabama,1007,22572.0,17590.0,74.765196,21.212121,2.223994,25.234804,1.351232,46.464646,...,87.471774,68.352607,1.0,6859,1559,5299,-0.551536,-0.466746,-0.520032,-0.542860
4,Alabama,1009,57704.0,42430.0,87.657701,1.557951,8.727298,12.342299,4.271801,50.485235,...,86.163610,89.951502,1.0,19391,1957,17420,-0.809090,-0.740940,-0.761559,-0.805394

In [35]:
#creating new column called "dem_win"
merged_df['dem_win'] = np.where(merged_df['vote1'] > merged_df['vote2'], 1, 0)
merged_df

,state,fips,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,...,rural_pct,ruralurban_cc,totalvote,vote1,vote2,pres_16_mov,pres_12_mov,sen_16_mov,house_16_mov,dem_win
0,Alabama,1001,55049.0,40690.0,75.683482,18.370906,2.572254,24.316518,1.838362,51.176225,...,42.002162,2.0,19665,6221,13400,-0.489969,-0.460304,-0.483037,-0.280756,0
1,Alabama,1003,199510.0,151770.0,83.178788,9.225603,4.366698,16.821212,3.269510,51.194928,...,42.279099,3.0,77829,17779,59992,-0.571601,-0.557688,-0.587449,-0.571601,0
2,Alabama,1005,26614.0,20375.0,45.885624,47.888329,4.309762,54.114376,2.859397,46.498084,...,67.789635,6.0,8354,4162,4191,-0.055688,0.031454,-0.064425,0.100637,0
3,Alabama,1007,22572.0,17590.0,74.765196,21.212121,2.223994,25.234804,1.351232,46.464646,...,68.352607,1.0,6859,1559,5299,-0.551536,-0.466746,-0.520032,-0.542860,0
4,Alabama,1009,57704.0,42430.0,87.657701,1.557951,8.727298,12.342299,4.271801,50.485235,...,89.951502,1.0,19391,1957,17420,-0.809090,-0.740940,-0.761559,-0.805394,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,44812.0,30565.0,79.815674,0.865840,15.859591,20.184326,5.509685,47.824244,...,10.916313,5.0,12753,3959,7700,-0.520899,-0.393844,NaN,-0.155873,0
3107,Wyoming,56039,22623.0,16335.0,81.200548,0.614419,15.174822,18.799452,11.475048,48.097069,...,46.430920,7.0,11622,7373,3843,0.268710,0.118196,NaN,0.236655,1
3108,Wyoming,56041,20893.0,14355.0,87.718375,0.186665,8.959939,12.281625,3.986981,49.327526,...,43.095937,7.0,6203,1256,4517,-0.584652,-0.584026,NaN,-0.450408,0
3109,Wyoming,56043,8351.0,6135.0,82.397318,0.790325,13.962400,17.602682,3.783978,51.359119,...,35.954529,7.0,3083,592,2263,-0.623755,-0.562880,NaN,-0.500388,0
3110,Wyoming,56045,7175.0,5565.0,92.222997,0.250871,1.003484,7.777003,4.083624,47.958188,...,54.536626,7.0,2665,372,2100,-0.775383,-0.714201,NaN,-0.514838,0

In [36]:
merged_df['dem_win'].value_counts()

dem_win
0    2438
1     660
Name: count, dtype: int64

In [37]:
final_drop_mov = ['vote1', 'vote2', 'totalvote', 'ruralurban_cc', 'white_pct', 'target_vic_size', 'dem_win', 'sen_16_mov']
mov_df = merged_df.copy()
mov_df['target_vic_size'] = mov_df['vote1'] - mov_df['vote2']
mov_df['target_mov'] = mov_df['target_vic_size'] / mov_df['totalvote']
mov_df = mov_df.drop(columns = final_drop_mov)

In [38]:
#dropping columns
final_drop = ['vote1', 'vote2', 'totalvote', 'ruralurban_cc', 'white_pct']
merged_df = merged_df.drop(columns = final_drop)
merged_df.head()

,state,fips,total_population,cvap,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,...,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,pres_16_mov,pres_12_mov,sen_16_mov,house_16_mov,dem_win
0,Alabama,1001,55049.0,40690.0,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,...,12.417046,75.407229,10.002112,74.065601,42.002162,-0.489969,-0.460304,-0.483037,-0.280756,0
1,Alabama,1003,199510.0,151770.0,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,...,9.972418,70.452889,7.842227,68.405607,42.279099,-0.571601,-0.557688,-0.587449,-0.571601,0
2,Alabama,1005,26614.0,20375.0,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,...,26.235928,87.132213,19.579752,81.364746,67.789635,-0.055688,0.031454,-0.064425,0.100637,0
3,Alabama,1007,22572.0,17590.0,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,...,19.301587,88.000000,15.020490,87.471774,68.352607,-0.551536,-0.466746,-0.520032,-0.542860,0
4,Alabama,1009,57704.0,42430.0,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,...,19.968585,86.950243,16.643368,86.163610,89.951502,-0.809090,-0.740940,-0.761559,-0.805394,0

In [39]:
#detect and remove the one nan value in 'cvap'
merged_df_nan_here = merged_df[merged_df['cvap'].isna()]
merged_df = merged_df.loc[~merged_df['fips'].isin(merged_df_nan_here['fips'])]

In [40]:
#creating a dataframe without the senate info
merged_df_no_sen = merged_df.drop(columns = 'sen_16_mov')
merged_df_no_sen

,state,fips,total_population,cvap,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,...,clf_unemploy_pct,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,pres_16_mov,pres_12_mov,house_16_mov,dem_win
0,Alabama,1001,55049.0,40690.0,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,...,5.591657,12.417046,75.407229,10.002112,74.065601,42.002162,-0.489969,-0.460304,-0.280756,0
1,Alabama,1003,199510.0,151770.0,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,...,6.286843,9.972418,70.452889,7.842227,68.405607,42.279099,-0.571601,-0.557688,-0.571601,0
2,Alabama,1005,26614.0,20375.0,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,...,12.824738,26.235928,87.132213,19.579752,81.364746,67.789635,-0.055688,0.031454,0.100637,0
3,Alabama,1007,22572.0,17590.0,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,...,7.146827,19.301587,88.000000,15.020490,87.471774,68.352607,-0.551536,-0.466746,-0.542860,0
4,Alabama,1009,57704.0,42430.0,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,...,5.953833,19.968585,86.950243,16.643368,86.163610,89.951502,-0.809090,-0.740940,-0.805394,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,44812.0,30565.0,0.865840,15.859591,20.184326,5.509685,47.824244,44.153352,...,5.072255,9.314606,78.628507,6.238463,76.606813,10.916313,-0.520899,-0.393844,-0.155873,0
3107,Wyoming,56039,22623.0,16335.0,0.614419,15.174822,18.799452,11.475048,48.097069,35.569995,...,2.123447,4.633570,46.211584,1.526877,41.769504,46.430920,0.268710,0.118196,0.236655,1
3108,Wyoming,56041,20893.0,14355.0,0.186665,8.959939,12.281625,3.986981,49.327526,43.205858,...,6.390755,10.361224,81.793082,8.806312,81.080852,43.095937,-0.584652,-0.584026,-0.450408,0
3109,Wyoming,56043,8351.0,6135.0,0.790325,13.962400,17.602682,3.783978,51.359119,34.774279,...,7.441860,12.577108,78.923920,10.299738,75.980688,35.954529,-0.623755,-0.562880,-0.500388,0
3110,Wyoming,56045,7175.0,5565.0,0.250871,1.003484,7.777003,4.083624,47.958188,33.282230,...,3.610949,8.592392,81.193281,7.342144,81.141179,54.536626,-0.775383,-0.714201,-0.514838,0

In [41]:
#creating new column to get the percentage of voters 18+
merged_df_no_sen['cvap_pct'] =  merged_df_no_sen['cvap']/merged_df_no_sen['total_population']
merged_df_no_sen

,state,fips,total_population,cvap,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,...,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,pres_16_mov,pres_12_mov,house_16_mov,dem_win,cvap_pct
0,Alabama,1001,55049.0,40690.0,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,...,12.417046,75.407229,10.002112,74.065601,42.002162,-0.489969,-0.460304,-0.280756,0,0.739160
1,Alabama,1003,199510.0,151770.0,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,...,9.972418,70.452889,7.842227,68.405607,42.279099,-0.571601,-0.557688,-0.571601,0,0.760714
2,Alabama,1005,26614.0,20375.0,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,...,26.235928,87.132213,19.579752,81.364746,67.789635,-0.055688,0.031454,0.100637,0,0.765575
3,Alabama,1007,22572.0,17590.0,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,...,19.301587,88.000000,15.020490,87.471774,68.352607,-0.551536,-0.466746,-0.542860,0,0.779284
4,Alabama,1009,57704.0,42430.0,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,...,19.968585,86.950243,16.643368,86.163610,89.951502,-0.809090,-0.740940,-0.805394,0,0.735304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,44812.0,30565.0,0.865840,15.859591,20.184326,5.509685,47.824244,44.153352,...,9.314606,78.628507,6.238463,76.606813,10.916313,-0.520899,-0.393844,-0.155873,0,0.682072
3107,Wyoming,56039,22623.0,16335.0,0.614419,15.174822,18.799452,11.475048,48.097069,35.569995,...,4.633570,46.211584,1.526877,41.769504,46.430920,0.268710,0.118196,0.236655,1,0.722053
3108,Wyoming,56041,20893.0,14355.0,0.186665,8.959939,12.281625,3.986981,49.327526,43.205858,...,10.361224,81.793082,8.806312,81.080852,43.095937,-0.584652,-0.584026,-0.450408,0,0.687072
3109,Wyoming,56043,8351.0,6135.0,0.790325,13.962400,17.602682,3.783978,51.359119,34.774279,...,12.577108,78.923920,10.299738,75.980688,35.954529,-0.623755,-0.562880,-0.500388,0,0.734643
3110,Wyoming,56045,7175.0,5565.0,0.250871,1.003484,7.777003,4.083624,47.958188,33.282230,...,8.592392,81.193281,7.342144,81.141179,54.536626,-0.775383,-0.714201,-0.514838,0,0.775610

In [42]:
#dropping the cvap column 
merged_df_no_sen = merged_df_no_sen.drop(columns='cvap')
merged_df_no_sen.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3097 entries, 0 to 3110
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3097 non-null   object
 1   fips                    3097 non-null   int64
 2   total_population        3097 non-null   float64
 3   black_pct               3097 non-null   float64
 4   hispanic_pct            3097 non-null   float64
 5   nonwhite_pct            3097 non-null   float64
 6   foreignborn_pct         3097 non-null   float64
 7   female_pct              3097 non-null   float64
 8   age29andunder_pct       3097 non-null   float64
 9   age65andolder_pct       3097 non-null   float64
 10  median_hh_inc           3097 non-null   float64
 11  clf_unemploy_pct        3097 non-null   float64
 12  lesshs_pct              3097 non-null   float64
 13  lesscollege_pct         3097 non-null   float64
 14  lesshs_whites_pct       3097 non-null   float64
 15  lesscollege_whites_pct  3097 non-null   float64
 16  rural_pct               3097 non-null   float64
 17  pres_16_mov             3097 non-null   float64
 18  pres_12_mov             3097 non-null   float64
 19  house_16_mov            3097 non-null   float64
 20  dem_win                 3097 non-null   int64
 21  cvap_pct                3097 non-null   float64
dtypes: float64(19), int64(2), object(1)
memory usage: 556.5+ KB

In [43]:
mov_df

,state,fips,total_population,cvap,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,...,clf_unemploy_pct,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,pres_16_mov,pres_12_mov,house_16_mov,target_mov
0,Alabama,1001,55049.0,40690.0,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,...,5.591657,12.417046,75.407229,10.002112,74.065601,42.002162,-0.489969,-0.460304,-0.280756,-0.365065
1,Alabama,1003,199510.0,151770.0,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,...,6.286843,9.972418,70.452889,7.842227,68.405607,42.279099,-0.571601,-0.557688,-0.571601,-0.542381
2,Alabama,1005,26614.0,20375.0,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,...,12.824738,26.235928,87.132213,19.579752,81.364746,67.789635,-0.055688,0.031454,0.100637,-0.003471
3,Alabama,1007,22572.0,17590.0,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,...,7.146827,19.301587,88.000000,15.020490,87.471774,68.352607,-0.551536,-0.466746,-0.542860,-0.545269
4,Alabama,1009,57704.0,42430.0,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,...,5.953833,19.968585,86.950243,16.643368,86.163610,89.951502,-0.809090,-0.740940,-0.805394,-0.797432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Wyoming,56037,44812.0,30565.0,0.865840,15.859591,20.184326,5.509685,47.824244,44.153352,...,5.072255,9.314606,78.628507,6.238463,76.606813,10.916313,-0.520899,-0.393844,-0.155873,-0.293343
3107,Wyoming,56039,22623.0,16335.0,0.614419,15.174822,18.799452,11.475048,48.097069,35.569995,...,2.123447,4.633570,46.211584,1.526877,41.769504,46.430920,0.268710,0.118196,0.236655,0.303734
3108,Wyoming,56041,20893.0,14355.0,0.186665,8.959939,12.281625,3.986981,49.327526,43.205858,...,6.390755,10.361224,81.793082,8.806312,81.080852,43.095937,-0.584652,-0.584026,-0.450408,-0.525713
3109,Wyoming,56043,8351.0,6135.0,0.790325,13.962400,17.602682,3.783978,51.359119,34.774279,...,7.441860,12.577108,78.923920,10.299738,75.980688,35.954529,-0.623755,-0.562880,-0.500388,-0.542005
3110,Wyoming,56045,7175.0,5565.0,0.250871,1.003484,7.777003,4.083624,47.958188,33.282230,...,3.610949,8.592392,81.193281,7.342144,81.141179,54.536626,-0.775383,-0.714201,-0.514838,-0.648405